name: "test"
on:
  push:
    branches: 
      - '**'
  pull_request:
    branches:
      - master
      - develop
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: npm ci
    - run: npm run build
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v1
    - run: npm ci
    - name: Run test with coverage
      run: npm run coverage
    - name: Generate coverage badges for client library
      uses: demyanets/angular-coverage-badges-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        coverage-summary-path: coverage/common/json-report/coverage-summary.json
        protected-branches: '["master", "develop"]'
        write-debug-logs: true
    - name: Generate coverage badges for common library
      uses: demyanets/angular-coverage-badges-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        coverage-summary-path: coverage/controller/json-report/coverage-summary.json
        protected-branches: '["master", "develop"]'
        write-debug-logs: true
    - name: Generate coverage badges for controller library
      uses: demyanets/angular-coverage-badges-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        coverage-summary-path: coverage/client/json-report/coverage-summary.json
        protected-branches: '["master", "develop"]'
        write-debug-logs: true
